# Site settings
title: jasql
email: cody.zuschlag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Cody Zuschlag
email: cody.zuschlag@gmail.com
facebook_username:
twitter_username: codyzus
github_username: codyzu
github_project: codyzu/jasql
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Cody Zuschlag

# API settings
google_api_key:

# Build settings
markdown: kramdown

exclude: ['vendor/bundle']